# Generated by Django 5.1.2 on 2024-10-17 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='borrowed_book',
            new_name='borrow_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='BooksManagement.category'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BooksManagement.book'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
